package(default_visibility = ["//visibility:public"])

java_library(
    name = "proto",
    srcs = glob(["*.java"]),
    deps = [
        "@com_google_code_findbugs_jsr305//jar",
        "@com_google_protobuf//:protobuf_java",
    ],
)
