package(default_visibility = ["//visibility:public"])

java_library(
    name = "proto",
    srcs = glob(["*.java"]),
    deps = [
        "@com_google_protobuf//:protobuf_java",
        "@jsr305_repo//jar",
    ],
)
