package(default_visibility = ["//visibility:public"])

java_library(
    name = "dealer",
    srcs = glob(["**/*.java"]),
    deps = [
        "//cards_proto:cards_java_proto",
        "//java/edu/nyu/cards",
        "@com_google_guava_guava//jar",
        "@jsr330_repo//jar",
    ],
)
