package(default_visibility = ["//visibility:public"])

java_library(
    name = "dealer",
    srcs = glob(["**/*.java"]),
    deps = [
        "//cards_proto:cards_proto_java",
        "//java/edu/nyu/cards",
        "@guava_repo//jar",
        "@jsr305_repo//jar",
        "@jsr330_repo//jar",
    ],
)
